name = "vivenu-event-monitor"
main = "src/index.ts"
compatibility_date = "2025-08-23"
compatibility_flags = ["global_fetch_strictly_public"]
account_id = "7b67476729e32b63bb323f64706075c0"

# KV Namespace for caching and rate limiting
[[kv_namespaces]]
binding = "KV"
id = "d40c6ee183574f0193a600ecfe00ecfc"
preview_id = "d40c6ee183574f0193a600ecfe00ecfc"

# KV Namespace for event discovery  
[[kv_namespaces]]
binding = "EVENT_IDS"
id = "2ad45f7d6f8b4d56887ec93d8e010426"
preview_id = "2ad45f7d6f8b4d56887ec93d8e010426"

# Scheduled cron trigger - runs daily at 4 AM UTC
[triggers]
crons = ["0 4 * * *"]

# Environment variables (non-sensitive)
[vars]
GOOGLE_SHEET_ID = "10dAtPhwPw3raEfSAbtCzMprVjCOHOctI-I1CASJeWFk"
ENVIRONMENT = "production"
READ_ONLY_KV = "true"

# Observability
[observability]
enabled = true

 

# Note: Sensitive data should be added via wrangler secrets:
# wrangler secret put VIVENU_SECRET
# wrangler secret put DACH_API
# wrangler secret put FRANCE_API
# wrangler secret put ITALY_API
# wrangler secret put BENELUX_API
# wrangler secret put USA_API
# wrangler secret put CANADA_API
# wrangler secret put AUSTRALIA_API
# wrangler secret put NORWAY_API
# wrangler secret put SWITZERLAND_API
# wrangler secret put GOOGLE_SERVICE_ACCOUNT_EMAIL
# wrangler secret put GOOGLE_PRIVATE_KEY